apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: promtail
  namespace: logging
spec:
  encryptedData:
    promtail.yaml: |-
      AgAlGYcRmbZbW9eh/GGZkm3gP+PSUxZC+p6LjYojbinLELr4qDuNMPAjKmJyKYXbD+fWUev3j/af/gAjKGtNAB1crM3oYd1+gZWcFmkIrUFXHUU9pyf+2t5t
      GJy+xAkrtwzCaFpw03R3oAponcYcAeYtAJ4qzJ6ibIqMy8zbUMl+xK7+uKRKJNMaMxWt0rp8AKkOcrqX+598iz94TChVVGkDH2feCuhGDwbBlIUAw3L015zy
      IO5g+Rou6WmGNUtZdcEf1Fv1P7puBI3J1pCdURIvslN9ZCwn/VCWz0YKzm5UWsH3vpdU4GE/VYwhMymE/AIwYfi8sAau+61USAZqTGAr3UyeZte/bzC51c3P
      z7gr46lCvF3o6N6rXUzkcM/KQUV1FwJfHQxiE7S4+nfWicrogIdJyw+mG9xJ6Rb8keqZqSLasUH9ZSV8Aw/DeevDJeDPkOGQBsnjfaCWUt4FtMC7lSqEHAeB
      KUcHsWfLZwdvpGWo2Hewl1Bw8wYzPqqxOnUKtvOYJOXLNU1/MUgX+Vi4UmJ6pVqGYcSQwQN3bDE2p2gxY6kMCZb97oaAaemPhopTCRG7B4EQ/1Gj0gj9xGXD
      7oHAkBMRtBgtfuY/GWvSIoZ7KtMeIw0hCeXWrsXLlmO0+ZgqgDt67bZq9RIdjb8A7YleWemdmCDm778peZdBNkemZWSEmGLJOHlY0emVtQJRchP0la1vzkYJ
      /nkxe94Drut6kQTpjgFnCaF4T3yjo3AbYgfcvZoY1i+fs75WUdDKejOoONHHatQQq0PPfd0an3Xb+CPp1X1eg2yKesiiL7+WqCrDiahmWrM55ayqAJzmI8xa
      oo4epvWWjuNizDVQR1/qWBZyZTV08bt/XDxHJYo9ODkB+96ujN7Noy4KsYYrmzGnqqYqfS9ZwkfbXBP3AoZLGjUtkrHiT9axvDBZbg1Go3ntlvqE2sGeTNcR
      iDZm5Y6rcdg2/O2pSrQockMrER5UUas8hXoC19Ftnf+pyQ78UU2oGZ/8pJmZdMYSLnwdWuXz6oLMaMQwpy98Um95ujfVwRiVEoWimFKXiunG8H3n9ZxzIcaK
      yxZK9yEJcLGjGbsJWXlsVaTd7/I1Lwn2RoH96aHNCpBZDynXtAnTtsclYJrN6iBNZptInesZJV5wQPJyUKvAHhBzk2mZZrXub6qeKupH6i0foCDZGomq7wvw
      0WSF9oToQ/bJtqBgyt7iVAfqr0Vj47o/2Py3F0d5suti0O44VoT1hlJz5ClttuL5KTlBTlx4J5nL61ymiCDdJK6YhG8K/KtJChC6jGHJAQlwFQtGXjIH3h81
      r7zwzPCEFtvVcIS/Tm89RQIKzO5M8i6KEscIdEobqVnUJpc56S3xIZht1kFo/Cx68zmqUdGXxOI/CT2a9XD4ZSIt6qgEELiAwYMVyhz+OO21u+8NqHBqFN4q
      jCOQ/sS26/kX1arcw2tYY7yFjECiTok446yuUVWPHlRXbTb+J92uqZsteXGhNCB+AdH45S7MLv3MBE1/7c26EEL8efnYc62PJel4d14PNy9yPRbHSdJxiFqc
      AT0w5JfDlAb3lTdttbYjH8SOBArlg4apFgpDnFib946Fg8oG8gCXbWKqExyyVu8UfqmATYjpiUfJx8xOL+cOKLFCkrifPNLgmFH56ctcM8UZ0KTrXueaEPId
      d9FDJLpdTYO6hUr9GA23tBpeNL+pV7+oqDTIptvgIOEFJzhiUj2UxV+8Bcc/j9FNBJf+JutzKPV8LSaW9sBIB/nHLmQldtk+xd6C17SjmXPuxMXos8n41d3u
      IjGaESWM4lmvPdKuPI7Dt9fBuK6YpJByn7tbTkqb0IqJPnguZhuqjY68BErgJ5tbcSzCwnScBrBIWyBbY7js4iS0ZGR83Ih3+rI4zqpyd0+wZrhTQuXvY+dp
      FKUmZE+GHfpU/IFjE76wbpI1PqKP0jCLeL4MYxSSYQOFyKwpYgLPIQdPgqQBXapomepIAAEa5prNKpGFPniag6prLaGnNoMUQWqoq9OS3x2QbNa22g5IOBgX
      eLjHcZZxXYbxs/fJo4UPf8gEw/REibrJjtVjdj/rJLhxK4Dx+56pPB2L0Lk+qfzhaauKmFGe7xaizK39VctXBNaChD4nnOdz+4WKd/Wt8U9Su6Z/3jkYcbq8
      lXfYNE98PVtL1Lfu8SFGNWMMMXbDkN2xSvT4D2ttwBo+Sn4Qv9NfazyDBPWthhqr/01m2Mu8rlF9XKlrYLFt06RVhyzBw85ZYGRFdehPZdVzCFjOx3OQsRNV
      PfsCRncKTTRpUybJ+Ado+zaBRFDGDgwD6PfI9lUXeXs3o31Q9O/dvJnJu9/FcQq0Y4Yy8Bk1oElsYVBrJnH5CkITMxEYZZ8yrtCtFp49wp+iQLXrrVfc9oJ9
      0sVE+2pNccSNh8JxNEKte+ApAEeRAWJOr3lg0orRNsZjISIuOuiRXlTAgzV+LnSQF1px8Dp8AP/r9y6CYo/9MLw8N8rV6MmlVye2DlKhZDLYtcOM+55FSq3N
      03p0gI+EC7MFVoh3zeIrfCV/HmvFTYPGUorl73tHVeOhXsptBGSWirpNG95m4zaFf8TZ1SVwtXG7I8fjTocZtm7zsUV/cHaBUAfveXPRKeDpTKBoZeR0kGrj
      q/BS6i0A49DTGNMFVoAh3tnZfRM+0B35rc2U5D0/XiljMsPAXbduuNB7pACy2YFLM+dgCLX49/zpqFfT7c53Uby5P1jCR+dF3K9hrgk+leKeAlfEMnTKFB4s
      QiBuIikl2h3QNLcGJT8pS8ph6dgdygDz5hd1RSOdTZDDdS25t2sox2raYgYl3SB8LBmxC43CtMnRPLpX6/kiT9xA0zksPC0aongIFXB0ca3NAg4clStSlqE9
      YndI2d2uE0ijv4EORDn6H8J7bLQFFbIQ50MNAHnU0V/ROw14THJv1kiNFvfWS1eKZYVBJ0/Py/i6+hTnXiKILOqpkqgSIdMrL3s72v/84bmHs21Ag6hcENDN
      saVdFNXQdz5WwuLOfg1lgHuOl0Ylox/GIswj5cRhHc0YOikoNdPdkzVx45onOSgSOydN9YPXwBeIfWxUAMX5cDzuCPjEbRpuMB2aaJpb0eoHqnE+N+RXInVZ
      jLx0k22Kw6H/ieDZmJsl8gfN/4yfA5335lcOxyn60niYrKe/069XD7hRcPVvaTwwhA5Z+RIt/ZSF2QifocwE/5ult4Nie/B9Vqg3Eh4Mz9aLMGAz9D+cnk+h
      LwnbyhMszgb8RSycZR17/uHJuSjwFcMHGl1OIv1YKdnK8CwmO32hxNM334CM2MDmbhXlYXeuUgQlVCxU3ri2OpBQtBbxZul9s02NvtB2DVJI3S7F4jNtKbiz
      CBjVeWGP9nP/N34TbOx94V0OmAgwPuI5JW+NgB9i7uSkDbLR1zjT/uPKkhQLdq4uTSry3OhS5lj+3VdzNdEZ96e0N5YwI7lwz5ApZt/IQNPyg2R2l/iLBnBm
      3hQseiRVb7YuoogzmGuDa/uHDiT0SF9loSkv404MJt/gc1Q6X1BwSHBIObk0Gie1i0x2Dniqb/ibfuLmZX1legi+Vpynb9+pnfc7tB24ZzhdQPKnpU5A7Qa9
      W9xBnd0AJ2oWu4I9BNBrYBEc/mHE/081arjFJudbnlSewg6WhXY2+Xl7b0+1d28jSOleU+MfcQeS5agmjkwsXO6wmM2UcAcnI2N2MKl9++zFMcf8u2ay+D30
      smnp4D+AxZSW9H1vqptEQrusUO3tDmBAekKIthkMJssNKZo8+pjQGDJT/n5bNUjn6Vp9NgHgk+Y5L/GOElqeOtjP7zyXxVOaZBDFVSjERJRPlyA9qlaP0D8X
      D/Qdv/wwoYxRU6gFLjsBfov/GcIKo6Wk15uoWK3Jfon9DkoPT46DA/GCujjjogByjEGilFRkIqO+2q8QkAkhQszSlLcGIoW+uGq9+f3HyMmmdQ28Y5WE60uz
      KMWiAm64quVnEFsp5ja6cudKROr2LwEaz1vywj6Kh7GNvwSi6eoKwy7W5abnHm9r8GdUBK2O9Qow2TjuahfP96SdVMZFSt4SD1vRDC6hWoFM9EaI2zt9rhS1
      dHLpreQF5IYbeiCFTpZbVEKVJf+iYYfPmFar5hXEesROXIFPK5DC5Yk8treDHAc3l6xsPs7j12UyB0FGm9Tx/eoRDGMVBXJKXaokOUfLoljRKXSyrt3p1EpC
      MhyzYVUHFu1C4pfHtHw26XAPlu02a/UjeY503Xzji+fvkdxjisNzs47c8m1Xj8Hs4XaClr5DQGE=
  template:
    metadata:
      name: |-
      promtail
      namespace: |-
      logging