apiVersion: v1
kind: Service
metadata:
  name: loki-gateway
  namespace: logging
  labels:
    app.kubernetes.io/name: loki-gateway
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3100
  selector:
    app.kubernetes.io/component: single-binary
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
  sessionAffinity: None
  type: ClusterIP
