apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailpit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jluisreyvargas/repo-infra.git
    targetRevision: main
    path: mailpit/base
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
