apiVersion: v1
kind: Service
metadata:
  name: listmonk-stable
  namespace: listmonk
  labels:
    app.kubernetes.io/name: listmonk
    app.kubernetes.io/part-of: listmonk2
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
  selector:
    app.kubernetes.io/name: listmonk
---
apiVersion: v1
kind: Service
metadata:
  name: listmonk-preview
  namespace: listmonk
  labels:
    app.kubernetes.io/name: listmonk
    app.kubernetes.io/part-of: listmonk2
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
  selector:
    app.kubernetes.io/name: listmonk
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: listmonk
  namespace: listmonk
  labels:
    app.kubernetes.io/name: listmonk
    app.kubernetes.io/part-of: listmonk2
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: listmonk
  template:
    metadata:
      labels:
        app.kubernetes.io/name: listmonk
        app.kubernetes.io/part-of: listmonk2
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: listmonk
          image: ghcr.io/jluisreyvargas/listmonk2:sha-fed5816e907e24bc55003084075d2ab6eda6caea
          imagePullPolicy: IfNotPresent
          command: ["sh", "-ec"]
          args:
            - |
              set -eu

              # Config en /tmp (rootfs read-only)
              cat > /tmp/config.toml <<EOF
              [app]
              address = "0.0.0.0:9000"
              # En listmonk v6 suele ser root_url, y en algunas builds también se lee como url.
              root_url = "${LISTMONK_APP_ROOT_URL}"
              url = "${LISTMONK_APP_ROOT_URL}"

              [db]
              host = "${DB_HOST}"
              port = ${DB_PORT}
              user = "${DB_USER}"
              password = "${DB_PASSWORD}"
              database = "${DB_NAME}"
              ssl_mode = "disable"
              max_open = 25
              max_idle = 25
              max_lifetime = "300s"
              EOF

              exec ./listmonk --config /tmp/config.toml
          ports:
            - containerPort: 9000
              name: http
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: listmonk
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: listmonk-secrets
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: listmonk-secrets
                  key: db_password
            - name: LISTMONK_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: listmonk-secrets
                  key: admin_user
            - name: LISTMONK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: listmonk-secrets
                  key: admin_password
            # Importante: SIN slash final
            - name: LISTMONK_APP_ROOT_URL
              value: "http://listmonk.local/"
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 20
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
  strategy:
    blueGreen:
      activeService: listmonk-stable
      previewService: listmonk-preview
      autoPromotionEnabled: false
      previewReplicaCount: 1
      scaleDownDelaySeconds: 30
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: listmonk
  namespace: listmonk
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: listmonk.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: listmonk-stable
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: listmonk-preview
  namespace: listmonk
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: preview.listmonk.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: listmonk-preview
                port:
                  number: 80
